### PR TITLE
remove specific sklearn dependence

### PR DESCRIPTION
**Pull request by dengemann**
Addresses #4 

@DavidSabbagh @agramfort

### CODE REVIEW

**Comment by dengemann** [comment]
Tests are passing on my M1 macbook -- using PyRiemann master

**Comment by agramfort** [comment]
it breaks the CIs

you need to adjust CI script so it installs pyriemann master

**Comment by dengemann** [comment]
> it breaks the CIs 

I figured that, let's see if last commit fixes it.

**Comment by agramfort** [comment]
Thx 🙏

**Pull request merged**
