### PR TITLE
Features selection and renaming

### PR DESCRIPTION
**Pull request by apmellot**

### CODE REVIEW

**Review by agramfort — COMMENTED** [review]
looks good !

**Comment by dengemann** [comment]
seems you have some problems with the linter .. style checking advised :)

**Comment by agramfort** [comment]
why did you close @dengemann ?

**Comment by dengemann** [comment]
It was not my intention ... weird.

**Comment by dengemann** [comment]
Thank you @apmellot !

fixed the remaining issue.

**Pull request merged**
